name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-mac:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build & publish macOS
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build && npx electron-builder --mac --x64 --arm64 --publish always

  release-win:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build & publish Windows
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build && npx electron-builder --win --publish always
